##
## Makefile for Igraph in /home/fillon_g/tp/igraph
## 
## Made by guillaume fillon
## Login   <fillon_g@epitech.net>
## 
## Started on  Thu Nov  8 09:41:26 2012 guillaume fillon
## Last update Mon Jan  7 18:54:41 2013 guillaume fillon
##

all:
	make -C.. all

clean:
	make -C.. clean

fclean: clean
	make -C.. fclean

re: fclean all

.PHONY: all clean fclean re
